### ISSUE TITLE
Encountered the following error after clicking Generate SQL

### ISSUE THREAD

**Issue by kj-1024** [whoiskatrin/sql-translator#59]
After creating a new table schema, I entered the following in the Human Language: “show me all student”, and encountered the following error after clicking Generate SQL. What is the reason for this issue?

Table Schema:
create table student(id int,name string);

**Comment by kj-1024** [comment]
Translate this natural language query into SQL without changing the case of the entries given by me:

"show me all student"

Use this table schema:

create table student(id int,name string);

SQL Query:
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async translateToSQL (/Users/keino/Desktop/ai/sql-translator/.next/server/pages/api/translate.js:69:22)
    at async handler (/Users/keino/Desktop/ai/sql-translator/.next/server/pages/api/translate.js:33:24)
    at async Object.apiResolver (/Users/keino/Desktop/ai/sql-translator/node_modules/next/dist/server/api-utils/node.js:363:9)
    at async NextNodeServer.runApi (/Users/keino/Desktop/ai/sql-translator/node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (/Users/keino/Desktop/ai/sql-translator/node_modules/next/dist/server/next-server.js:750:37)
    at async Router.execute (/Users/keino/Desktop/ai/sql-translator/node_modules/next/dist/server/router.js:253:36)
    at async NextNodeServer.run (/Users/keino/Desktop/ai/sql-translator/node_modules/next/dist/server/base-server.js:384:29)
    at async NextNodeServer.handleRequest (/Users/keino/Desktop/ai/sql-translator/node_modules/next/dist/server/base-server.js:322:20) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:6869:28)
      at node:internal/deps/undici/undici:6825:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:6857:13)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
